language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=dev-master

before_script: 
  - sudo apt-get install geoip-bin
  - sudo apt-get install geoip-database
  - sudo apt-get install libgeoip-dev
  - ls -l /usr/share/GeoIP
  - wget https://github.com/downloads/lunetics/TimezoneBundle/GeoLiteCity.dat.gz
  - gunzip GeoLiteCity.dat.gz
  - sudo mkdir -p /usr/share/GeoIP
  - sudo mv GeoLiteCity.dat /usr/share/GeoIP/GeoIPCity.dat
  - pecl install geoip
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update --dev
  - composer install --dev --prefer-source 

script: 
  - phpunit --coverage-text --coverage-clover=coverage.clover /home/travis/build/azine/geoblocking-bundle/Tests/
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: travis@azine-it.ch



