language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=dev-master


before_script: 
    - composer update --dev --prefer-source
    - composer install
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source
  

script: phpunit -c app  vendor/azine/ --coverage-text

notifications:
  email: travis@azine-it.ch



