language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=dev-master

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master

  exclude:
      - php: 5.3
            env: SYMFONY_VERSION=dev-master
      - php: 5.4
            env: SYMFONY_VERSION=dev-master


before_script: 
  - sudo apt-get install geoip-bin
  - sudo apt-get install geoip-database
  - sudo apt-get install libgeoip-dev
  - ls -l /usr/share/GeoIP
  - wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
  - gunzip GeoLiteCity.dat.gz
  - sudo mkdir -p /usr/share/GeoIP
  - sudo mv GeoLiteCity.dat /usr/share/GeoIP/GeoIPCity.dat
  - pecl install geoip
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update --dev -v
  - composer -vvv install --dev --prefer-source

script: 
  - phpunit --coverage-text --coverage-clover=coverage.clover /home/travis/build/azine/geoblocking-bundle/Tests/
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: travis@azine-it.ch



